---
title: "Implementing automated section control sprayers for optimising pesticide application in orchards"
author: "Clemens Stephany, Christoph Weinmann, Lucas Hoffmann, Adrian Fülle, Jasper Hackling"
date: "6/1/2021"
output: html_document
---

\ 

#### Description   
A decision analysis on optimizing pesticide application in orchards with an LIDAR sensor and an automated section controlled sprayer.

\ 

#### Decision maker: farmer   
* Farmer is the main stakeholder who makes the decision whether or not to buy a modern sprayer which is able to minimise pesticide application rates

\ 

#### Stake holders: (describe further)
* farmers 
* manufacturers 
* government 
* consumers 
* society 
* food retailers 
* water suppliers 
* agrochemical companies 
* NGOs 
* local biodiversity
* beekeepers

\ 

#### Problems:    
* Some common agrochemicals will be banned in the near future for various reasons
  + overuse causes problems 
  + public opinion is getting worse   
* Excessive use of pesticides can cause unwanted effects (e.g. resistances)  
* Agrochemicals are costly supplies $\Rightarrow$ reduction is welcome  

\ 

#### Options:  
* No change 
* Spray less pesticide with existing machinery 
* Adopt organic farming practices 
* Use beneficiaries (beneficial organisms)
* Spray manually 
* Buy automatic section control sprayer
* Buy manual section control sprayer

\ 

#### Allocation of resources:  
* Money
  + Overheads
  + Running costs 
* Labour 
  + Conducting actual tasks 
  + Acquiring know-how
* Pollinators  

\ 

#### Obstacles:  
* Costs of investment


#### Uncertainties:  
* Potential reduction of pesticides using an automatic section controlled sprayer
  + especially the reduction of excessive pesticides
* Common application rates of pesticides in orchards
* Potential Cost of an automatic section controlled sprayer
* Changing climate influencing the frequency of pesticides application
* Increased bee survival rate (as there still are pesticides, just less)
* Added value through increased bee survival and thus increasing pollination
* Governmental interest in pesticides reduction
* Image of a farmer trying to reduce pesticides but still using them
* Maintenance cost of an more complicated and sensitive system

#### (Sources of) information:
* Farmers
  + 
* Manufacturer (Currently developing a prototype)
  + Cost and capabilities of an automatic section controlled sprayer
* Landwirtschaftskammer NRW
  + potential subsidisation of automatic section controlled sprayer
  + political foreshadowing of future legislations
* (commercial) Beekeepers
  + How much of an problem are pesticides
* Consumers
  + access the importance of an image





 